---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - podadm.sysadm.cn
  resources:
  - podadms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - podadm.sysadm.cn
  resources:
  - podadms/finalizers
  verbs:
  - update
- apiGroups:
  - podadm.sysadm.cn
  resources:
  - podadms/status
  verbs:
  - get
  - patch
  - update
